# Generated by Django 2.0.6 on 2018-07-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_useravatarurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='createdDate',
            field=models.CharField(default='', max_length=10),
        ),
    ]
